[package]
name = "hello-github-actions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "hello-github-actions"
path = "src/main.rs"

[dependencies]
actix-web = "4"
