app: hest-er-best
shortname: hest
team: plattform
ingress:
  enabled: false
container:
  cpu: 0.2
  memory: 128
  probes:
    spec:
      startupProbe:
        httpGet:
            path: /
            port: 8080
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 30
      readinessProbe:
        httpGet:
            path: /
            port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
    liveness:
      path: "/"
    readiness:
      path: "/"
  prometheus:
    enabled: false
env: dev
deployment:
  replicas: 5