apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hestekur-prd
commonLabels:
  environment: prd
commonAnnotations:
  note: Marta i farta
resources:
- ../../base
- serviceaccount.yaml
helmCharts:
- name: common
  namespace: hestekur-dev
  releaseName: hest-er-best-med-helm
  repo: https://entur.github.io/helm-charts
  valuesFile: values-prd.yaml
  valuesInline:
    container:
      image: app-image
  version: 1.17.3
images:
- name: app-image
  newName: europe-west1-docker.pkg.dev/ent-getstarted-sbx/getting-started-github-actions/hello-github-actions
  newTag: v0.2.0-build.31.1
