name: "Build and tag Dev"
on:
  push:
    branches:
      - "main"
env:
  IMAGE: "eu.gcr.io/entur-system-1287/hest-er-best"
  VERSION: "pr-11"
  ENV: "dev"

jobs:
  update-image-tag:
    name: "Update Image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kustomize
          kustomize: '5.2.1'
      - name: "Update Deployment Image Tag" # [3]
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          kustomize edit set image app-image=${{ env.IMAGE }}:${{ env.VERSION }}
      - name: "Push Updated Image Tag ${{ env.ENV }}"
        id: git-push-changes
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          if [[ $(git status --porcelain .) ]]; then
            git add .
            git config --global user.name "@github-actions-bot"
            git config --global user.email "github-actions-bot@users.noreply.github.com"
            git commit -m "feat: Update deployment image tag in ${{ env.ENV }} to ${{ env.VERSION }} [skip ci]"
            git push
            echo "::set-output name=pushed::true"
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
      - name: Version
        if: steps.git-push-changes.outputs.pushed == 'true'
        id: version
        uses: juliansangillo/tag-version@v1
        with:
            dev-branch: main
