name: "Build and tag Dev"
on:
  push:
    branches:
      - "main"
env:
  ENV: "dev"
  VERSION: "v0.1.${{github.run_number}}.${{ github.run_attempt }}"
  CARGO_TERM_COLOR: always
  PROJECT_ID: ent-getstarted-sbx
  DOCKER_URL: europe-west1-docker.pkg.dev
  WORKLOAD_IDENTITY_PROVIDER: "projects/475080371789/locations/global/workloadIdentityPools/poc-gh-actions-pool/providers/poc-gh-actions-provider"
  SERVICE_ACCOUNT: "github-actions-poc@ent-getstarted-sbx.iam.gserviceaccount.com"
  IMAGE_PATH: "ent-getstarted-sbx/getting-started-github-actions/hello-github-actions"

jobs:
  docker-build:
    name: "Build Docker Image"
    permissions:
      contents: 'write'  # for google auth
      id-token: 'write' # for google auth
      actions: none
      checks: none
      deployments: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          show-progress: false
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release --target=x86_64-unknown-linux-musl
      - name: Prepare Binary
        run: |
          # reduce size
          strip target/x86_64-unknown-linux-musl/release/hello-github-actions
          # move and rename
          mv target/x86_64-unknown-linux-musl/release/hello-github-actions target/release/hello-github-actions-musl
          # make executable
          chmod +x target/release/hello-github-actions-musl

      # TODO
      - name: "Authenticate with Google Cloud"
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{env.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{env.SERVICE_ACCOUNT}}
      # SDK
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      # Docker config
      - name: 'Configure Docker with gcloud auth'
        run: gcloud --quiet auth configure-docker ${{env.DOCKER_URL}}
      # Docker build
      - name: "Docker Build"
        run: |-
          docker build \
            --tag "${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}:latest" \
            --tag "${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}:${{github.sha}}" \
            --tag "${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}:${{env.VERSION}}" \
            --tag "${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}:${{env.ENV}}_${{env.VERSION}}" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      # Docker publish
      - name: Docker Publish
        run: |-
          docker push -a "${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}"

  update-image-tag:
    name: "Update Image & Tag"
    permissions:
      contents: 'write'
      id-token: 'none'
      actions: none
      checks: none
      deployments: none
      issues: none
      discussions: none
      packages: none
      pages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    needs: docker-build
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          show-progress: false
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kustomize
          kustomize: '5.2.1'
      - name: "Update Deployment Image Tag" # [3]
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          kustomize edit set image app-image=${{env.DOCKER_URL}}/${{env.IMAGE_PATH}}:${{ env.VERSION }}
      - name: "Push Updated Image Tag ${{ env.ENV }}"
        id: git-push-changes
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          if [[ $(git status --porcelain .) ]]; then
            git add .
            git config --global user.name "@github-actions-bot"
            git config --global user.email "github-actions-bot@users.noreply.github.com"
            git commit -m "feat: Update deployment image tag in ${{ env.ENV }} to ${{ env.VERSION }} [skip ci]"
            git tag -a "${{ env.VERSION }}" -m "Update deployment image tag in ${{ env.ENV }} to ${{ env.VERSION }}"
            git tag -a "${{ env.ENV }}" -m "Update environment tag ${{ env.ENV }}"
            git push
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_OUTPUT
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.previousTag.outputs.previousTag }}
          writeToFile: true
          reverseOrder: true
          excludeTypes: build,docs,other,style,chore(deps),ci,refactor,test


