name: "Prod release"
on:
  push:
    branches:
      - main
    tags:
      - '*' # Push events to matching tags only
env:
  IMAGE: "eu.gcr.io/entur-system-1287/hest-er-best"
  VERSION: "pr-2"
  ENV: "prd"

jobs:
  update-image-tag:
    name: "Update Image"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Git checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kustomize
          kustomize: '5.2.1'
      - name: "Update Deployment Image Tag"
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          kustomize edit set image app-image=${{ env.IMAGE }}:${{ env.VERSION }}
      - name: "Push Updated Image Tag ${{ env.ENV }}"
        id: git-push-changes
        working-directory: ".argo/hestekur/overlays/${{ env.ENV }}"
        run: |
          if [[ $(git status --porcelain .) ]]; then
            git config --global user.name "@github-actions-bot"
            git config --global user.email "github-actions-bot@users.noreply.github.com"
            git config --global --add --bool push.autoSetupRemote true
            git checkout -b "prod-release-${{ env.VERSION }}"
            git add .
            git commit -m "feat: Update deployment image tag in ${{ env.ENV }} to ${{ env.VERSION }} [skip ci]"
            git push
            echo "::set-output name=pushed::true"
          else
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
      - name: "Create Pull Request"
        if: steps.git-push-changes.outputs.pushed == 'true'
        run: |
          gh pr create -B main -H "prod-release-${{ env.VERSION }}" --title 'Merge prod-release-${{ env.VERSION }} into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
